# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 00:38
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='developer',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='portfolio.Developer', verbose_name='developer'
            ),
        ),
    ]
