# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 03:18
from __future__ import unicode_literals

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_field_developer_on_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='name')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
            },
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['start_date', 'title'], 'verbose_name': 'entry', 'verbose_name_plural': 'entries'},
        ),
        migrations.RemoveField(
            model_name='entry',
            name='date',
        ),
        migrations.AddField(
            model_name='developer',
            name='behance',
            field=models.URLField(blank=True, verbose_name='behance'),
        ),
        migrations.AddField(
            model_name='developer',
            name='bitbucket',
            field=models.URLField(blank=True, verbose_name='bitbucket'),
        ),
        migrations.AddField(
            model_name='developer',
            name='description',
            field=models.TextField(default='', verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='developer',
            name='facebook',
            field=models.URLField(blank=True, verbose_name='facebook'),
        ),
        migrations.AddField(
            model_name='developer',
            name='instagram',
            field=models.URLField(blank=True, verbose_name='instagram'),
        ),
        migrations.AddField(
            model_name='developer',
            name='phone_number',
            field=models.CharField(default='', max_length=20, verbose_name='phone number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='developer',
            name='skills',
            field=models.ManyToManyField(to='portfolio.Tag', verbose_name='tags'),
        ),
        migrations.AddField(
            model_name='entry',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='end date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='start date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='website',
            field=models.URLField(blank=True, verbose_name='website'),
        ),
        migrations.AddField(
            model_name='testimony',
            name='entry',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='portfolio.Entry', verbose_name='entry'
            ),
        ),
        migrations.AddField(
            model_name='entry',
            name='customer',
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE, to='portfolio.Customer',
                verbose_name='customer'
            ),
            preserve_default=False,
        ),
    ]
